# requiring necessary packages
library('fpp2')
library('xts')
library('data.table')
library('ggpubr')
library('seasonal')
library(urca)
library(repr)
options(repr.plot.width=9, repr.plot.height=2)
options(warn=-1)